#!/usr/bin/bash

# init
/bin/busybox mount -t proc		none	/proc
/bin/busybox mount -t sysfs		none	/sys
/bin/busybox mount -t devtmpfs	none	/dev

/bin/busybox --install

sleep 1

# do stuff
export PATH=/sbin:/usr/sbin:/bin:/usr/bin
export USER=root
clear
sethostname neofetch-linux
neofetch
echo -n '# '
while read -r line; do
	if [ $line = "neofetch" ]; then
		neofetch
	else
		echo "error: invalid command!"
		echo "valid commands are:"
		echo "	neofetch"
	fi
	echo -n '# '
done

# uninit
umount /dev
umount /sys
umount /proc
